version: '3'

services:
  seq:
    restart: always      
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8005:80"
  db:
    restart: always
    image: task-management/db
    build:
      dockerfile: Dockerfile.compose
      context: ./database
    ports:
      - "1437:1433"
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    command: ["sh", "/usr/config/entrypoint.sh"]
  client:
    restart: always
    image: task-management/client
    build:
      dockerfile: Dockerfile.stage
      context: ./client
    container_name: client
    environment:
      - API_URL=api;
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    restart: always
    image: task-management/api
    build:
      dockerfile: Dockerfile.stage
      context: ./api
    container_name: api
    environment:
      - ConnectionStrings__TasksDb=Server=db;DataBase=Tasks;User Id=sa;Password=P@ssw0rd;Connection Timeout=30;
      - Seq=http://seq/
    ports:
      - "5000:5000"
    depends_on:
      - db
      - seq