apiVersion: v1
kind: Service
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: kibana
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Kibana
  name: kibana-cluster-ip-service
  namespace: logging
spec:
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP