apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 5
  selector:
    matchLabels: 
      component: mssql
  template:
    metadata:
      labels:
        component: mssql
    spec:
      volumes:
        - name: mssql-storage
          persistentVolumeClaim: 
            claimName: database-persistent-volume-claim
      containers: 
        - name: mssql
          image: ddydeveloper/task-management-mssql
          command: ["sh", "/usr/config/entrypoint.sh"]
          ports:
            - containerPort: 1433         
          volumeMounts:
           - name: mssql-storage
             mountPath: /var/opt/mssql/data
             subPath: mssql
          env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
