apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: mssql
  template:
    metadata:
      labels:
        component: mssql
    spec:
      volumes:
        - name: mssql-storage
          persistentVolumeClaim: 
            claimName: database-persistent-volume-claim
      containers: 
        - name: mssql
          image: ddydeveloper/task-management-mssql
          command: ["/opt/mssql/bin/sqlservr", "/opt/mssql-tools/bin/sqlcmd"]
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
