apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: mssql
  template:
    metadata:
      labels:
        component: mssql
    spec:
      containers: 
        - name: mssql
          image: ddydeveloper/task-management-mssql
          ports:
            - containerPort: 1433
