apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 4
  selector:
    matchLabels: 
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers: 
        - name: server
          image: ddydeveloper/task-management-server
          ports:
            - containerPort: 5000
          env:
            - name: Seq
              value: "http://seq-cluster-ip-service"
            - name: ConnectionStrings__TasksDb
              # value: "Server=mssql-cluster-ip-service;DataBase=Tasks;User Id=sa;Password=P@ssword;Connection Timeout=30;" 
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: TASKS_DB  
            - name: ConnectionStrings__Redis
              value: "redis-cluster-ip-service"