apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers: 
        - name: server
          image: ddydeveloper/task-management-server
          ports:
            - containerPort: 5000
          env:
            - name: ConnectionStrings__TasksDb
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: TASKS_DB
            - name: ConnectionStrings__ElasticSearch
              value: http://elasticsearch-client.logging.svc.cluster.local
            - name: ConnectionStrings__Redis
              value: redis-cluster-ip-service