FROM microsoft/mssql-server-linux

RUN mkdir -p /usr/config
COPY ./data /usr/config

RUN chmod +x /usr/config/entrypoint.sh

ENV SA_PASSWORD=P@ssw0rd
ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Developer

CMD ["sh", "/usr/config/entrypoint.sh"]