FROM microsoft/mssql-server-linux

RUN mkdir -p /opt/mssql-scripts

COPY ./post-deployment.sql /opt/mssql-scripts
COPY ./data.csv /opt/mssql-scripts

ENV SA_PASSWORD=P@ssw0rd
ENV ACCEPT_EULA=Y

RUN ( /opt/mssql/bin/sqlservr --accept-eula & ) | grep -q "Service Broker manager has started" \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'P@ssw0rd' -i/opt/mssql-scripts/post-deployment.sql \
    && pkill sqlservr 
